name: Авто-обновление отчета

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-report:
    runs-on: ubuntu-latest

    steps:
    - name: Клонирование кода
      uses: actions/checkout@v4

    - name: Настройка Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Установка библиотек
      run: pip install requests gspread openpyxl python-dotenv

    - name: Запуск скрипта генерации
      env:
        DIRECT_TOKEN: ${{ secrets.DIRECT_TOKEN }}
        METRIKA_TOKEN: ${{ secrets.METRIKA_TOKEN }}
        GOOGLE_SHEET_URL: ${{ secrets.GOOGLE_SHEET_URL }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > credentials.json
        python generate_report.py
